name: NDS Build with BlocksDS

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build NDS project
        run: |
          docker pull skylyrac/blocksds
          docker run --rm -v "$(pwd):/workspace" -w /workspace/source skylyrac/blocksds make

      - name: Upload NDS artifact
        uses: actions/upload-artifact@v4
        with:
          name: nds-build
          path: |
            source/*.nds
            source/*.elf
          if-no-files-found: warn
